name: ImAnalyst
dependencies:
- astroid=1.3.4=py35_0
- django=1.8.4=py35_0
- fontconfig=2.11.1=4
- freetype=2.5.2=2
- jpeg=8d=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libtiff=4.0.2=1
- libxml2=2.9.2=0
- logilab-common=0.63.2=py35_0
- matplotlib=1.4.3=np110py35_2
- numpy=1.10.1=py35_0
- openblas=0.2.14=3
- openssl=1.0.1k=1
- pillow=3.0.0=py35_0
- pip=7.1.2=py35_0
- pylint=1.4.2=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_0
- python=3.5.0=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.6=py35_0
- qt=4.8.7=1
- readline=6.2=2
- setuptools=18.4=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - django-bootstrap3==6.2.2
  - psycopg2==2.6.1
  - uwsgi==2.0.11.2

